// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpd8JymJKRQgmPzz2anTwLvbYlCiDA0q8',
    appId: '1:982955236133:web:f9a34b9ce6c90ea87ad8cc',
    messagingSenderId: '982955236133',
    projectId: 'crudoperation-6f4bc',
    authDomain: 'crudoperation-6f4bc.firebaseapp.com',
    storageBucket: 'crudoperation-6f4bc.appspot.com',
    measurementId: 'G-LY3M3GSSJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE-cXf7mqXb3kSGI7SwPtPu0xkJRKKMls',
    appId: '1:982955236133:android:deeac470cbc00c5e7ad8cc',
    messagingSenderId: '982955236133',
    projectId: 'crudoperation-6f4bc',
    storageBucket: 'crudoperation-6f4bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6LltqUPcEStNvTJU44L5KkvFaGlxPIY',
    appId: '1:982955236133:ios:a9e40b834a2e899b7ad8cc',
    messagingSenderId: '982955236133',
    projectId: 'crudoperation-6f4bc',
    storageBucket: 'crudoperation-6f4bc.appspot.com',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6LltqUPcEStNvTJU44L5KkvFaGlxPIY',
    appId: '1:982955236133:ios:a9e40b834a2e899b7ad8cc',
    messagingSenderId: '982955236133',
    projectId: 'crudoperation-6f4bc',
    storageBucket: 'crudoperation-6f4bc.appspot.com',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpd8JymJKRQgmPzz2anTwLvbYlCiDA0q8',
    appId: '1:982955236133:web:f4fb736394810ac17ad8cc',
    messagingSenderId: '982955236133',
    projectId: 'crudoperation-6f4bc',
    authDomain: 'crudoperation-6f4bc.firebaseapp.com',
    storageBucket: 'crudoperation-6f4bc.appspot.com',
    measurementId: 'G-1QXR1NE8T2',
  );
}
